import { TextStyle } from "./EditorTextTools";

export type TextPresetKey =
  | "titulo"
  | "subtitulo"
  | "cintillo"
  | "lower_third"
  | "oferta";

export const TEXT_PRESETS: Record<TextPresetKey, TextStyle> = {
  titulo: {
    content: "Título principal",
    fontFamily: "Montserrat",
    fontSize: 84,
    fontWeight: 800,
    color: "#FFFFFF",
    lineHeight: 1.05,
    letterSpacing: 0.2,
    textAlign: "left",
    textIndent: 0,
    paddingX: 28,
    paddingY: 20,
    bannerStyle: "gradient",
    bannerColor: "#6D28D9",
    bannerFrom: "#6D28D9",
    bannerTo: "#EC4899",
    borderRadius: 16,
  },
  subtitulo: {
    content: "Subtítulo descriptivo",
    fontFamily: "Inter",
    fontSize: 46,
    fontWeight: 600,
    color: "#F8FAFC",
    lineHeight: 1.2,
    letterSpacing: 0.1,
    textAlign: "left",
    textIndent: 0,
    paddingX: 24,
    paddingY: 16,
    bannerStyle: "solid",
    bannerColor: "#111827",
    bannerFrom: "#111827",
    bannerTo: "#111827",
    borderRadius: 12,
  },
  cintillo: {
    content: "PROMOCIÓN HOY",
    fontFamily: "Poppins",
    fontSize: 40,
    fontWeight: 700,
    color: "#111827",
    lineHeight: 1.1,
    letterSpacing: 1.2,
    textAlign: "center",
    textIndent: 0,
    paddingX: 30,
    paddingY: 14,
    bannerStyle: "solid",
    bannerColor: "#FDE047",
    bannerFrom: "#FDE047",
    bannerTo: "#FDE047",
    borderRadius: 999,
  },
  lower_third: {
    content: "Sucursal Centro  |  2x1 en combos",
    fontFamily: "Inter",
    fontSize: 34,
    fontWeight: 600,
    color: "#FFFFFF",
    lineHeight: 1.15,
    letterSpacing: 0.2,
    textAlign: "left",
    textIndent: 0,
    paddingX: 26,
    paddingY: 14,
    bannerStyle: "gradient",
    bannerColor: "#0F172A",
    bannerFrom: "#0F172A",
    bannerTo: "#334155",
    borderRadius: 10,
  },
  oferta: {
    content: "50% OFF",
    fontFamily: "Montserrat",
    fontSize: 96,
    fontWeight: 800,
    color: "#FFFFFF",
    lineHeight: 1,
    letterSpacing: 0.5,
    textAlign: "center",
    textIndent: 0,
    paddingX: 34,
    paddingY: 24,
    bannerStyle: "gradient",
    bannerColor: "#DC2626",
    bannerFrom: "#DC2626",
    bannerTo: "#F97316",
    borderRadius: 20,
  },
};

export const PRESET_LABELS: Record<TextPresetKey, string> = {
  titulo: "Título",
  subtitulo: "Subtítulo",
  cintillo: "Cintillo",
  lower_third: "Lower Third",
  oferta: "Oferta",
};
