// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-screens.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated" }],
    isError: true
  };
}

// src/lib/mcp/tools/list-screens.ts
var list_screens_default = defineTool({
  name: "list_screens",
  title: "List screens",
  description: "List digital-signage screens the signed-in Visualia user can see (respects business membership and RLS). Returns id, name, status, location and last_seen.",
  inputSchema: {
    status: z.enum(["online", "offline", "pending", "all"]).optional().describe("Filter by screen status. Defaults to 'all'."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("screens").select("id, name, status, last_seen_at, location_id, locations(name)").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status && status !== "all") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = (data ?? []).map((r) => ({
      id: r.id,
      name: r.name,
      status: r.status,
      last_seen_at: r.last_seen_at,
      location: r.locations?.name ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { screens: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/list-locations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_locations_default = defineTool2({
  name: "list_locations",
  title: "List locations",
  description: "List the signed-in user's business locations (branches).",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { data, error } = await supabaseForUser(ctx).from("locations").select("id, name, address, latitude, longitude, created_at").order("created_at", { ascending: false }).limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { locations: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-content.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_content_default = defineTool3({
  name: "list_content",
  title: "List content items",
  description: "List content assets (images, videos, designs) available to the signed-in user's business.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { data, error } = await supabaseForUser(ctx).from("content").select("id, name, type, file_url, thumbnail_url, duration_seconds, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-subscription.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_subscription_default = defineTool4({
  name: "get_subscription",
  title: "Get subscription status",
  description: "Return the current subscription plan, screen count, pricing and billing dates for the signed-in user's business.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("subscriptions").select(
      "id, plan, status, screens_count, billing_cycle, price_per_screen, total_amount, billing_anchor, next_billing_date, expires_at, grace_period_ends_at, updated_at"
    ).order("updated_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { subscription: data ?? null }
    };
  }
});

// src/lib/mcp/tools/generate-image.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";

// src/lib/mcp/ai-studio-bridge.ts
async function callAiStudio(path, body, token) {
  const url = process.env.SUPABASE_URL;
  const resp = await fetch(`${url}/functions/v1/ai-studio/${path}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${token}`,
      "X-Visualia-Source": "mcp"
    },
    body: JSON.stringify(body)
  });
  const text = await resp.text();
  const data = text ? JSON.parse(text) : {};
  if (!resp.ok) {
    throw new Error(data.error ?? `ai-studio ${resp.status}`);
  }
  return data;
}

// src/lib/mcp/tools/generate-image.ts
var generate_image_default = defineTool5({
  name: "generate_image",
  title: "Generar imagen para pantalla",
  description: "Genera una imagen profesional para digital signage (men\xFA, promoci\xF3n, bienvenida). Aplica el brand kit del negocio del usuario a menos que se indique lo contrario.",
  inputSchema: {
    prompt: z4.string().min(3).describe("Descripci\xF3n en espa\xF1ol de la imagen a generar."),
    formato: z4.enum(["16:9", "9:16", "1:1", "4:5"]).default("16:9").describe("Formato de pantalla objetivo."),
    marca_de_agua_off: z4.boolean().optional().describe("Desactiva el watermark discreto de Visualia (solo planes premium)."),
    apply_brand_kit: z4.boolean().optional().describe("Aplica autom\xE1ticamente colores/logo del brand kit del negocio.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado." }], isError: true };
    }
    const out = await callAiStudio(
      "generate_image",
      {
        prompt: input.prompt,
        formato: input.formato,
        watermark_off: input.marca_de_agua_off ?? false,
        apply_brand_kit: input.apply_brand_kit ?? true
      },
      ctx.getToken()
    );
    return {
      content: [{ type: "text", text: `Imagen generada: ${out.url}` }],
      structuredContent: out
    };
  }
});

// src/lib/mcp/tools/generate-video-loop.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
var generate_video_loop_default = defineTool6({
  name: "generate_video_loop",
  title: "Generar loop corto para pantalla",
  description: "Genera una pieza en loop corta (3\u201315s) para digital signage. Devuelve la URL del asset y su duraci\xF3n. Aplica el brand kit del negocio.",
  inputSchema: {
    prompt: z5.string().min(3).describe("Descripci\xF3n de la escena en loop."),
    duracion_segundos: z5.number().int().min(3).max(15).default(6),
    formato: z5.enum(["16:9", "9:16", "1:1"]).default("16:9")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado." }], isError: true };
    }
    const out = await callAiStudio(
      "generate_video_loop",
      input,
      ctx.getToken()
    );
    return {
      content: [{ type: "text", text: `Loop ${out.duracion_segundos}s listo: ${out.url}` }],
      structuredContent: out
    };
  }
});

// src/lib/mcp/tools/suggest-copy.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^3.25.76";
var suggest_copy_default = defineTool7({
  name: "suggest_copy",
  title: "Sugerir copy de promoci\xF3n",
  description: "Genera t\xEDtulo, subt\xEDtulo y CTA para una promoci\xF3n usando el contexto real del negocio del usuario (nombre, segmento).",
  inputSchema: {
    tipo_promocion: z6.string().min(2).describe("Ej: 'happy hour cerveza', 'men\xFA del d\xEDa', 'apertura'."),
    contexto_negocio: z6.string().optional().describe("Contexto adicional opcional; si no se env\xEDa se toma del perfil del negocio.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado." }], isError: true };
    }
    const out = await callAiStudio(
      "suggest_copy",
      input,
      ctx.getToken()
    );
    const c = out.copy ?? {};
    return {
      content: [{ type: "text", text: `${c.titulo ?? ""}
${c.subtitulo ?? ""}
${c.cta ?? ""}`.trim() }],
      structuredContent: out
    };
  }
});

// src/lib/mcp/tools/apply-brand-kit.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z7 } from "npm:zod@^3.25.76";
var apply_brand_kit_default = defineTool8({
  name: "apply_brand_kit",
  title: "Reaplicar brand kit al asset",
  description: "Toma un asset generado previamente y lo re-genera aplicando los colores, logo y watermark del brand kit del negocio. \xDAtil cuando la primera generaci\xF3n no respet\xF3 la marca.",
  inputSchema: {
    asset_id: z7.string().uuid().describe("ID de una generaci\xF3n previa del propio negocio."),
    tenant_id: z7.string().uuid().optional().describe("Legacy; ignorado. El tenant siempre se deriva del token del usuario.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado." }], isError: true };
    }
    const out = await callAiStudio(
      "apply_brand_kit",
      { generation_id: input.asset_id },
      ctx.getToken()
    );
    return {
      content: [{ type: "text", text: `Asset con brand kit aplicado: ${out.url}` }],
      structuredContent: out
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ovuhtroiuuqsiltqgqpp";
var mcp_default = defineMcp({
  name: "visualia-mcp",
  title: "Visualia",
  version: "0.2.0",
  instructions: "Herramientas para la plataforma Visualia de digital signage. Consultan el negocio del usuario (pantallas, sedes, biblioteca, suscripci\xF3n) y generan contenido de IA (im\xE1genes, loops, copy) con el brand kit del tenant. Todo el acceso respeta la membres\xEDa del usuario v\xEDa Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_screens_default,
    list_locations_default,
    list_content_default,
    get_subscription_default,
    generate_image_default,
    generate_video_loop_default,
    suggest_copy_default,
    apply_brand_kit_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
