// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-screens.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated" }],
    isError: true
  };
}

// src/lib/mcp/tools/list-screens.ts
var list_screens_default = defineTool({
  name: "list_screens",
  title: "List screens",
  description: "List digital-signage screens the signed-in Visualia user can see (respects business membership and RLS). Returns id, name, status, location and last_seen.",
  inputSchema: {
    status: z.enum(["online", "offline", "pending", "all"]).optional().describe("Filter by screen status. Defaults to 'all'."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("screens").select("id, name, status, last_seen_at, location_id, locations(name)").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (status && status !== "all") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rows = (data ?? []).map((r) => ({
      id: r.id,
      name: r.name,
      status: r.status,
      last_seen_at: r.last_seen_at,
      location: r.locations?.name ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { screens: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/list-locations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_locations_default = defineTool2({
  name: "list_locations",
  title: "List locations",
  description: "List the signed-in user's business locations (branches).",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { data, error } = await supabaseForUser(ctx).from("locations").select("id, name, address, city, created_at").order("created_at", { ascending: false }).limit(limit ?? 100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { locations: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/list-content.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_content_default = defineTool3({
  name: "list_content",
  title: "List content items",
  description: "List content items (images, videos, designs) available to the signed-in user's business.",
  inputSchema: {
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const { data, error } = await supabaseForUser(ctx).from("content_items").select("id, name, type, url, thumbnail_url, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { items: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-subscription.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_subscription_default = defineTool4({
  name: "get_subscription",
  title: "Get subscription status",
  description: "Return the current subscription plan, screen count, and billing status for the signed-in user's business.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("subscriptions").select("id, plan, status, screen_count, current_period_start, current_period_end, updated_at").order("updated_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { subscription: data ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ovuhtroiuuqsiltqgqpp";
var mcp_default = defineMcp({
  name: "visualia-mcp",
  title: "Visualia",
  version: "0.1.0",
  instructions: "Tools for the Visualia digital-signage platform. Use these to inspect the signed-in user's screens, locations, content library, and subscription. All tools respect the user's business membership via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_screens_default, list_locations_default, list_content_default, get_subscription_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
